// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"context"
	"encoding/json/v2"
	"errors"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Habitica API Library (github.com/go-api-libs/habitica)"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "habitica.com",
}

// Client is an HTTP client for the habitica API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The API key
	apiKey string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithAPIKey returns a [ClientOption] that sets a custom API key.
func WithAPIKey(apiKey string) ClientOption {
	return func(c *Client) { c.apiKey = apiKey }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	c.apiKey = os.Getenv("HABITICA_API_KEY")

	for _, opt := range opts {
		opt(c)
	}

	if c.apiKey == "" {
		return nil, errors.New("api key HABITICA_API_KEY not provided")
	}

	return c, nil
}

// GET /api/v3/tasks/user
func (c *Client) ListTasks(ctx context.Context, params *ListTasksParams) (*TaskList, error) {
	return ListTasks[TaskList](ctx, c, params)
}

// GET /api/v3/tasks/user
func ListTasks[R any](ctx context.Context, c *Client, params *ListTasksParams) (*R, error) {
	u := c.baseURL.JoinPath("api", "v3", "tasks", "user")

	if params != nil {
		q := make(url.Values, 1)

		if params.Type != "" {
			q["type"] = []string{params.Type}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"X-Client":   []string{"8027d396-e2bb-4389-b002-782025424e75-go-api-libs/habitica"},
			"X-Api-Key":  []string{},
			"X-Api-User": []string{},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
