// This file provides tests for the client.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"bytes"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"io"
	"maps"
	"net/http"
	"net/http/httptest"
	"net/url"
	"slices"
	"testing"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
	"github.com/go-api-libs/api"
	"github.com/google/uuid"
)

func newTestServer(t *testing.T, status int) *httptest.Server {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(status)
	}))
	t.Cleanup(srv.Close)
	return srv
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}

func TestClient_Error(t *testing.T) {
	t.Run("GetUser", func(t *testing.T) {
		t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetUser(t.Context(), GetUserParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetUser(t.Context(), GetUserParams{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetUser(t.Context(), GetUserParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetUser(t.Context(), GetUserParams{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("ListTasks", func(t *testing.T) {
		t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListTasks(t.Context(), ListTasksParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListTasks(t.Context(), ListTasksParams{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListTasks(t.Context(), ListTasksParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ListTasks(t.Context(), ListTasksParams{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("GetTaskByID", func(t *testing.T) {
		t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetTaskByID(t.Context(), uuid.Nil, GetTaskByIDParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetTaskByID(t.Context(), uuid.Nil, GetTaskByIDParams{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetTaskByID(t.Context(), uuid.Nil, GetTaskByIDParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.GetTaskByID(t.Context(), uuid.Nil, GetTaskByIDParams{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("ScoreTask", func(t *testing.T) {
		t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ScoreTask(t.Context(), uuid.Nil, "", ScoreTaskParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ScoreTask(t.Context(), uuid.Nil, "", ScoreTaskParams{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ScoreTask(t.Context(), uuid.Nil, "", ScoreTaskParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.ScoreTask(t.Context(), uuid.Nil, "", ScoreTaskParams{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("Cast", func(t *testing.T) {
		t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cast(t.Context(), "", CastParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cast(t.Context(), "", CastParams{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cast(t.Context(), "", CastParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cast(t.Context(), "", CastParams{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("BuyHealthPotion", func(t *testing.T) {
		t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.BuyHealthPotion(t.Context(), BuyHealthPotionParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.BuyHealthPotion(t.Context(), BuyHealthPotionParams{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.BuyHealthPotion(t.Context(), BuyHealthPotionParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.BuyHealthPotion(t.Context(), BuyHealthPotionParams{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})

	t.Run("Cron", func(t *testing.T) {
		t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

		t.Run("transport error", func(t *testing.T) {
			c, err := NewClient(WithHTTPClient(&http.Client{Transport: roundTripFunc(
				func(*http.Request) (*http.Response, error) { return nil, io.EOF },
			)}))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cron(t.Context(), CronParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, io.EOF) {
				t.Fatalf("want: %v, got: %v", io.EOF, err)
			}
		})

		t.Run("unknown status code", func(t *testing.T) {
			srv := newTestServer(t, http.StatusTeapot)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cron(t.Context(), CronParams{}); err == nil {
				t.Fatal("expected error")
			} else if apiErr, ok := errors.AsType[*api.Error](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if apiErr.Err != api.ErrUnknownStatusCode {
				t.Fatalf("got: %v, want: %v", apiErr.Err, api.ErrUnknownStatusCode)
			} else if apiErr.Response.StatusCode != http.StatusTeapot {
				t.Fatalf("got: %v, want: %v", apiErr.Response.StatusCode, http.StatusTeapot)
			}
		})

		t.Run("unknown content type", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "foo")
				w.WriteHeader(http.StatusOK)
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cron(t.Context(), CronParams{}); err == nil {
				t.Fatal("expected error")
			} else if !errors.Is(err, api.ErrUnknownContentType) {
				t.Fatalf("want: %v, got: %v", api.ErrUnknownContentType, err)
			}
		})

		t.Run("decoding error", func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_, _ = w.Write([]byte("invalid json"))
			}))
			t.Cleanup(srv.Close)

			baseURL, err := url.Parse(srv.URL)
			if err != nil {
				t.Fatal(err)
			}

			c, err := NewClient(WithBaseURL(baseURL))
			if err != nil {
				t.Fatal(err)
			}

			if _, err := c.Cron(t.Context(), CronParams{}); err == nil {
				t.Fatal("expected error")
			} else if decErr, ok := errors.AsType[*api.DecodingError](err); !ok {
				t.Fatalf("got: %T, want: *api.Error", err)
			} else if _, ok := errors.AsType[*jsontext.SyntacticError](decErr.Err); !ok {
				t.Fatalf("got: %T, want: *jsontext.SyntacticError", decErr.Err)
			}
		})
	})
}

func replay(t *testing.T) http.RoundTripper {
	t.Helper()

	interactions, err := cassette.InteractionsReadFile("../../api/interactions.json")
	if err != nil {
		t.Fatal(err)
	}

	var idx int
	return roundTripFunc(func(req *http.Request) (*http.Response, error) {
		if idx >= len(interactions) {
			return nil, fmt.Errorf("unexpected request: %s %s", req.Method, req.URL)
		}

		ia := interactions[idx]

		r, err := cassette.NewRequest(req)
		if err != nil {
			return nil, err
		}

		if r.URL != ia.Request.URL {
			return nil, fmt.Errorf("interaction #%d: got URL %s, want %s", idx, r.URL, ia.Request.URL)
		}

		if r.Method != ia.Request.Method {
			return nil, fmt.Errorf("interaction #%d: got method %s, want %s", idx, r.Method, ia.Request.Method)
		}

		if !bytes.Equal(r.Body, ia.Request.Body) {
			return nil, fmt.Errorf("interaction #%d: got body %s, want %s", idx, string(r.Body), string(ia.Request.Method))
		}

		if ia.Request.Headers == nil {
			ia.Request.Headers = http.Header{}
		}

		if ia.Request.Headers.Get("User-Agent") == "" {
			ia.Request.Headers.Set("User-Agent", defaultUserAgent)
		}

		if !maps.EqualFunc(r.Headers, ia.Request.Headers, slices.Equal) {
			return nil, fmt.Errorf("interaction #%d: got headers %s, want %s", idx, r.Headers, ia.Request.Headers)
		}

		idx++
		return &http.Response{
			Status:     fmt.Sprintf("%d %s", ia.Response.StatusCode, http.StatusText(ia.Response.StatusCode)),
			StatusCode: ia.Response.StatusCode,
			Header:     ia.Response.Headers.Clone(),
			Body:       io.NopCloser(bytes.NewReader(ia.Response.Body)),
		}, nil
	})
}

func TestClient_Interactions(t *testing.T) {
	ctx := t.Context()
	t.Setenv("HABITICA_API_KEY", "00000000-0000-0000-0000-000000000000")

	c, err := NewClient(WithHTTPClient(&http.Client{Transport: replay(t)}))
	if err != nil {
		t.Fatal(err)
	}

	if _, err := c.ListTasks(ctx, ListTasksParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("ListTasks: %v", err)
	}

	if _, err := c.GetTaskByID(ctx, uuid.MustParse("2b774d70-ec8b-41c1-8967-eb6b13d962ba"), GetTaskByIDParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("GetTaskByID: %v", err)
	}

	if _, err := c.GetUser(ctx, GetUserParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("GetUser: %v", err)
	}

	if _, err := c.ScoreTask(ctx, uuid.MustParse("2b774d70-ec8b-41c1-8967-eb6b13d962ba"), "up", ScoreTaskParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("ScoreTask: %v", err)
	}

	if _, err := c.ScoreTask(ctx, uuid.MustParse("4f2d942d-67e8-4cc0-ac08-61962296660b"), "up", ScoreTaskParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err == nil {
		t.Fatal("ScoreTask: expected error")
	} else if _, ok := errors.AsType[*Error](err); !ok {
		t.Fatalf("ScoreTask: got: %T, want: *Error", err)
	}

	if _, err := c.ScoreTask(ctx, uuid.MustParse("488a92c0-164c-445a-be31-1bcb1b04ab04"), "up", ScoreTaskParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("ScoreTask: %v", err)
	}

	if _, err := c.Cast(ctx, "smash", CastParams{
		TargetID: uuid.MustParse("f7591dce-398a-4e12-ba23-18542f9f0bef"),
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("Cast: %v", err)
	}

	if _, err := c.Cast(ctx, "smash", CastParams{
		TargetID: uuid.MustParse("f7591dce-398a-4e12-ba23-18542f9f0bef"),
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err == nil {
		t.Fatal("Cast: expected error")
	} else if _, ok := errors.AsType[*Error](err); !ok {
		t.Fatalf("Cast: got: %T, want: *Error", err)
	}

	if _, err := c.BuyHealthPotion(ctx, BuyHealthPotionParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("BuyHealthPotion: %v", err)
	}

	if _, err := c.Cron(ctx, CronParams{
		XAPIUser: uuid.MustParse("b0413351-405f-416f-8787-947ec1c85199"),
	}); err != nil {
		t.Fatalf("Cron: %v", err)
	}
}
