// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"context"
	"encoding/json/v2"
	"errors"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Habitica API Library (github.com/go-api-libs/habitica)"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "habitica.com",
	Path:   "/api/v3",
}

// Client is an HTTP client for the habitica API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The API key
	apiKey string
	// The client parameter
	client string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithAPIKey returns a [ClientOption] that sets a custom API key.
func WithAPIKey(apiKey string) ClientOption {
	return func(c *Client) { c.apiKey = apiKey }
}

// WithClient returns a [ClientOption] that sets a custom client parameter.
func WithClient(client string) ClientOption {
	return func(c *Client) { c.client = client }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		client:    "b0413351-405f-416f-8787-947ec1c85199-go-api-libs/habitica",
		userAgent: defaultUserAgent,
	}

	c.apiKey = os.Getenv("HABITICA_API_KEY")

	for _, opt := range opts {
		opt(c)
	}

	if c.apiKey == "" {
		return nil, errors.New("api key HABITICA_API_KEY not provided")
	}

	if c.client == "" {
		return nil, errors.New("client parameter not provided")
	}

	return c, nil
}

// The user profile contains data related to the authenticated user including (but not limited to): Achievements; Authentications (including types and timestamps); Challenges memberships (Challenge IDs); Flags (including armoire, tutorial, tour etc...); Guilds memberships (Guild IDs); History (including timestamps and values, only for Experience and summed To Do values); Inbox; Invitations (to parties/guilds); Items (character's full inventory); New Messages (flags for party/guilds that have new messages; also reported in Notifications); Notifications; Party (includes current quest information); Preferences (user selected prefs); Profile (name, photo url, blurb); Purchased (includes subscription data and some gem-purchased items); PushDevices (identifiers for mobile devices authorized); Stats (standard RPG stats, class, buffs, xp, etc..); Tags; TasksOrder (list of all IDs for Dailys, Habits, Rewards and To Do's).
//
//	GET /user
func (c *Client) GetUser(ctx context.Context, params GetUserParams) (*User, error) {
	return GetUser[User](ctx, c, params)
}

// The user profile contains data related to the authenticated user including (but not limited to): Achievements; Authentications (including types and timestamps); Challenges memberships (Challenge IDs); Flags (including armoire, tutorial, tour etc...); Guilds memberships (Guild IDs); History (including timestamps and values, only for Experience and summed To Do values); Inbox; Invitations (to parties/guilds); Items (character's full inventory); New Messages (flags for party/guilds that have new messages; also reported in Notifications); Notifications; Party (includes current quest information); Preferences (user selected prefs); Profile (name, photo url, blurb); Purchased (includes subscription data and some gem-purchased items); PushDevices (identifiers for mobile devices authorized); Stats (standard RPG stats, class, buffs, xp, etc..); Tags; TasksOrder (list of all IDs for Dailys, Habits, Rewards and To Do's).
// You can define a custom result to unmarshal the response into.
//
//	GET /user
func GetUser[R any](ctx context.Context, c *Client, params GetUserParams) (*R, error) {
	u := c.baseURL.JoinPath("user")
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /tasks/user
func (c *Client) ListTasks(ctx context.Context, params ListTasksParams) (*TasksResponse, error) {
	return ListTasks[TasksResponse](ctx, c, params)
}

// GET /tasks/user
func ListTasks[R any](ctx context.Context, c *Client, params ListTasksParams) (*R, error) {
	u := c.baseURL.JoinPath("tasks", "user")

	q := make(url.Values, 1)

	if params.Type != "" {
		q["type"] = []string{params.Type}
	}

	u.RawQuery = q.Encode()

	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Get a task
//
//	GET /tasks/{taskId}
func (c *Client) GetTaskByID(ctx context.Context, taskID string, params GetTaskByIDParams) (*TaskResponse, error) {
	return GetTaskByID[TaskResponse](ctx, c, taskID, params)
}

// Get a task
// You can define a custom result to unmarshal the response into.
//
//	GET /tasks/{taskId}
func GetTaskByID[R any](ctx context.Context, c *Client, taskID string, params GetTaskByIDParams) (*R, error) {
	u := c.baseURL.JoinPath("tasks", taskID)
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
