// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"context"
	"encoding/json/v2"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/MarkRosemaker/openapi-enrich/cassette"
	"github.com/go-api-libs/api"
	"github.com/google/uuid"
)

const defaultUserAgent = "Habitica API Library (github.com/go-api-libs/habitica)"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "habitica.com",
	Path:   "/api/v3",
}

// Client is an HTTP client for the habitica API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The API key
	apiKey string
	// The client parameter
	client string
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// WithAPIKey returns a [ClientOption] that sets a custom API key.
func WithAPIKey(apiKey string) ClientOption {
	return func(c *Client) { c.apiKey = apiKey }
}

// WithClient returns a [ClientOption] that sets a custom client parameter.
func WithClient(client string) ClientOption {
	return func(c *Client) { c.client = client }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		client:    "b0413351-405f-416f-8787-947ec1c85199-go-api-libs/habitica",
		userAgent: defaultUserAgent,
	}

	c.apiKey = os.Getenv("HABITICA_API_KEY")

	for _, opt := range opts {
		opt(c)
	}

	if c.apiKey == "" {
		return nil, errors.New("api key HABITICA_API_KEY not provided")
	}

	if c.client == "" {
		return nil, errors.New("client parameter not provided")
	}

	return c, nil
}

// The user profile contains data related to the authenticated user including (but not limited to): Achievements; Authentications (including types and timestamps); Challenges memberships (Challenge IDs); Flags (including armoire, tutorial, tour etc...); Guilds memberships (Guild IDs); History (including timestamps and values, only for Experience and summed To Do values); Inbox; Invitations (to parties/guilds); Items (character's full inventory); New Messages (flags for party/guilds that have new messages; also reported in Notifications); Notifications; Party (includes current quest information); Preferences (user selected prefs); Profile (name, photo url, blurb); Purchased (includes subscription data and some gem-purchased items); PushDevices (identifiers for mobile devices authorized); Stats (standard RPG stats, class, buffs, xp, etc..); Tags; TasksOrder (list of all IDs for Dailys, Habits, Rewards and To Do's).
//
//	GET /user
func (c *Client) GetUser(ctx context.Context, params GetUserParams) (*User, error) {
	return c.GetUserWithResult[User](ctx, params)
}

// The user profile contains data related to the authenticated user including (but not limited to): Achievements; Authentications (including types and timestamps); Challenges memberships (Challenge IDs); Flags (including armoire, tutorial, tour etc...); Guilds memberships (Guild IDs); History (including timestamps and values, only for Experience and summed To Do values); Inbox; Invitations (to parties/guilds); Items (character's full inventory); New Messages (flags for party/guilds that have new messages; also reported in Notifications); Notifications; Party (includes current quest information); Preferences (user selected prefs); Profile (name, photo url, blurb); Purchased (includes subscription data and some gem-purchased items); PushDevices (identifiers for mobile devices authorized); Stats (standard RPG stats, class, buffs, xp, etc..); Tags; TasksOrder (list of all IDs for Dailys, Habits, Rewards and To Do's).
// You can define a custom result to unmarshal the response into.
//
//	GET /user
func (c *Client) GetUserWithResult[R any](ctx context.Context, params GetUserParams) (*R, error) {
	u := c.baseURL.JoinPath("user")
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	ia.Request, err = cassette.NewRequest(req)
	if err != nil {
		return nil, fmt.Errorf("recording request: %w", err)
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	ia.Response, err = cassette.NewResponse(rsp)
	if err != nil {
		return nil, fmt.Errorf("recording response: %w", err)
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /tasks/user
func (c *Client) ListTasks(ctx context.Context, params ListTasksParams) (*TasksResponse, error) {
	return c.ListTasksWithResult[TasksResponse](ctx, params)
}

// GET /tasks/user
func (c *Client) ListTasksWithResult[R any](ctx context.Context, params ListTasksParams) (*R, error) {
	u := c.baseURL.JoinPath("tasks", "user")

	q := make(url.Values, 1)

	if params.Type != "" {
		q["type"] = []string{params.Type}
	}

	u.RawQuery = q.Encode()

	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	ia.Request, err = cassette.NewRequest(req)
	if err != nil {
		return nil, fmt.Errorf("recording request: %w", err)
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	ia.Response, err = cassette.NewResponse(rsp)
	if err != nil {
		return nil, fmt.Errorf("recording response: %w", err)
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusBadRequest:
		// An error returned by the server, e.g. Not Found
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out Error
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Get a task
//
//	GET /tasks/{taskId}
func (c *Client) GetTaskByID(ctx context.Context, taskID uuid.UUID, params GetTaskByIDParams) (*TaskResponse, error) {
	return c.GetTaskByIDWithResult[TaskResponse](ctx, taskID, params)
}

// Get a task
// You can define a custom result to unmarshal the response into.
//
//	GET /tasks/{taskId}
func (c *Client) GetTaskByIDWithResult[R any](ctx context.Context, taskID uuid.UUID, params GetTaskByIDParams) (*R, error) {
	u := c.baseURL.JoinPath("tasks", taskID.String())
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	ia.Request, err = cassette.NewRequest(req)
	if err != nil {
		return nil, fmt.Errorf("recording request: %w", err)
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	ia.Response, err = cassette.NewResponse(rsp)
	if err != nil {
		return nil, fmt.Errorf("recording response: %w", err)
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Score a task
//
//	POST /tasks/{taskId}/score/{direction}
func (c *Client) ScoreTask(ctx context.Context, taskID uuid.UUID, direction string, params ScoreTaskParams) (*ScoreTaskResponse, error) {
	return c.ScoreTaskWithResult[ScoreTaskResponse](ctx, taskID, direction, params)
}

// Score a task
// You can define a custom result to unmarshal the response into.
//
//	POST /tasks/{taskId}/score/{direction}
func (c *Client) ScoreTaskWithResult[R any](ctx context.Context, taskID uuid.UUID, direction string, params ScoreTaskParams) (*R, error) {
	u := c.baseURL.JoinPath("tasks", taskID.String(), "score", direction)
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodPost,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	ia.Request, err = cassette.NewRequest(req)
	if err != nil {
		return nil, fmt.Errorf("recording request: %w", err)
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	ia.Response, err = cassette.NewResponse(rsp)
	if err != nil {
		return nil, fmt.Errorf("recording response: %w", err)
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusNotFound:
		// An error returned by the server, e.g. Not Found
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out Error
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Cast a skill (spell) on a target
//
//	POST /user/class/cast/{spellId}
func (c *Client) Cast(ctx context.Context, spellID string, params CastParams) (*CastResponse, error) {
	return c.CastWithResult[CastResponse](ctx, spellID, params)
}

// Cast a skill (spell) on a target
// You can define a custom result to unmarshal the response into.
//
//	POST /user/class/cast/{spellId}
func (c *Client) CastWithResult[R any](ctx context.Context, spellID string, params CastParams) (*R, error) {
	u := c.baseURL.JoinPath("user", "class", "cast", spellID)

	q := make(url.Values, 1)

	if params.TargetID != uuid.Nil {
		q["targetId"] = []string{params.TargetID.String()}
	}

	u.RawQuery = q.Encode()

	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodPost,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	ia.Request, err = cassette.NewRequest(req)
	if err != nil {
		return nil, fmt.Errorf("recording request: %w", err)
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	ia.Response, err = cassette.NewResponse(rsp)
	if err != nil {
		return nil, fmt.Errorf("recording response: %w", err)
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusUnauthorized:
		// An error returned by the server, e.g. Not Found
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out Error
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrCustom(rsp, &out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// POST /user/buy-health-potion
func (c *Client) BuyHealthPotion(ctx context.Context, params BuyHealthPotionParams) (*BuyHealthPotionResponse, error) {
	return c.BuyHealthPotionWithResult[BuyHealthPotionResponse](ctx, params)
}

// POST /user/buy-health-potion
func (c *Client) BuyHealthPotionWithResult[R any](ctx context.Context, params BuyHealthPotionParams) (*R, error) {
	u := c.baseURL.JoinPath("user", "buy-health-potion")
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodPost,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	ia.Request, err = cassette.NewRequest(req)
	if err != nil {
		return nil, fmt.Errorf("recording request: %w", err)
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	ia.Response, err = cassette.NewResponse(rsp)
	if err != nil {
		return nil, fmt.Errorf("recording response: %w", err)
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// This causes cron to run. It assumes that the user has already been shown the Record Yesterday's Activity ("Check off any Dailies you did yesterday") screen and so it will immediately apply damage for incomplete due Dailies.
//
//	POST /cron
func (c *Client) Cron(ctx context.Context, params CronParams) (*CronResponse, error) {
	return c.CronWithResult[CronResponse](ctx, params)
}

// This causes cron to run. It assumes that the user has already been shown the Record Yesterday's Activity ("Check off any Dailies you did yesterday") screen and so it will immediately apply damage for incomplete due Dailies.
// You can define a custom result to unmarshal the response into.
//
//	POST /cron
func (c *Client) CronWithResult[R any](ctx context.Context, params CronParams) (*R, error) {
	u := c.baseURL.JoinPath("cron")
	req := (&http.Request{
		Header: http.Header{
			"X-Api-Key":  []string{c.apiKey},
			"X-Client":   []string{c.client},
			"X-Api-User": []string{params.XAPIUser.String()},
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodPost,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	var (
		ia  cassette.Interaction
		err error
	)
	ia.Request, err = cassette.NewRequest(req)
	if err != nil {
		return nil, fmt.Errorf("recording request: %w", err)
	}
	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	ia.Response, err = cassette.NewResponse(rsp)
	if err != nil {
		return nil, fmt.Errorf("recording response: %w", err)
	}

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				if err2 := cassette.AddInteraction("api/interactions.json", ia); err2 != nil {
					return nil, errors.Join(api.WrapDecodingError(rsp, err), err2)
				}

				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
