// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"encoding/json/v2"
	"time"

	"github.com/google/uuid"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// ListTasksParams holds the query parameters for ListTasks.
type ListTasksParams struct {
	Type string
}

// Approval defines a model
type Approval struct {
	Required  bool `json:"required,omitzero"`
	Approved  bool `json:"approved,omitzero"`
	Requested bool `json:"requested,omitzero"`
}

// Group defines a model
type Group struct {
	Approval         Approval   `json:"approval"`
	AssignedUsers    []struct{} `json:"assignedUsers,omitempty"`
	SharedCompletion string     `json:"sharedCompletion,omitzero"`
	CompletedBy      *struct{}  `json:"completedBy,omitempty"`
}

// Task defines a model
type Task struct {
	UnderscoreID      uuid.UUID   `json:"_id,omitzero"`
	Challenge         struct{}    `json:"challenge"`
	Group             Group       `json:"group"`
	Up                bool        `json:"up,omitzero"`
	Down              bool        `json:"down,omitzero"`
	CounterUp         int         `json:"counterUp,omitzero"`
	CounterDown       int         `json:"counterDown,omitzero"`
	Frequency         string      `json:"frequency,omitzero"`
	History           TaskHistory `json:"history,omitempty"`
	Type              string      `json:"type,omitzero"`
	Notes             string      `json:"notes,omitzero"`
	Tags              []uuid.UUID `json:"tags,omitempty"`
	Value             float64     `json:"value"`
	Priority          float64     `json:"priority"`
	Attribute         string      `json:"attribute,omitzero"`
	ByHabitica        bool        `json:"byHabitica,omitzero"`
	Text              string      `json:"text,omitzero"`
	Reminders         []struct{}  `json:"reminders,omitempty"`
	CreatedAt         time.Time   `json:"createdAt,omitzero"`
	UpdatedAt         time.Time   `json:"updatedAt,omitzero"`
	UserID            uuid.UUID   `json:"userId,omitzero"`
	ID                uuid.UUID   `json:"id,omitzero"`
	Repeat            *TaskRepeat `json:"repeat,omitempty"`
	EveryX            *int        `json:"everyX,omitempty"`
	Streak            *int        `json:"streak,omitempty"`
	NextDue           []time.Time `json:"nextDue,omitempty"`
	YesterDaily       bool        `json:"yesterDaily,omitempty"`
	Completed         bool        `json:"completed,omitempty"`
	CollapseChecklist bool        `json:"collapseChecklist,omitempty"`
	StartDate         time.Time   `json:"startDate,omitempty"`
	DaysOfMonth       []struct{}  `json:"daysOfMonth,omitempty"`
	WeeksOfMonth      []struct{}  `json:"weeksOfMonth,omitempty"`
	Checklist         []struct{}  `json:"checklist,omitempty"`
	IsDue             bool        `json:"isDue,omitempty"`
}

// TaskActivity defines a model
type TaskActivity struct {
	Date       int     `json:"date,omitzero"`
	Value      float64 `json:"value"`
	ScoredUp   int     `json:"scoredUp,omitzero"`
	ScoredDown int     `json:"scoredDown,omitzero"`
}

// TaskHistory defines a model
type TaskHistory []TaskActivity

// TaskList defines a model
type TaskList struct {
	Success       bool       `json:"success,omitzero"`
	Data          Tasks      `json:"data,omitempty"`
	Notifications []struct{} `json:"notifications,omitempty"`
	UserV         int        `json:"userV,omitzero"`
	AppVersion    string     `json:"appVersion,omitzero"`
}

// TaskRepeat defines a model
type TaskRepeat struct {
	M  bool `json:"m,omitzero"`
	T  bool `json:"t,omitzero"`
	W  bool `json:"w,omitzero"`
	Th bool `json:"th,omitzero"`
	F  bool `json:"f,omitzero"`
	S  bool `json:"s,omitzero"`
	Su bool `json:"su,omitzero"`
}

// Tasks defines a model
type Tasks []Task
