// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package habitica

import (
	"encoding/json/v2"
	"time"

	"github.com/google/uuid"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
)

// ListTasks defines a model
type ListTasks struct {
	Success       bool          `json:"success,omitzero"`
	Data          ListTasksData `json:"data,omitempty"`
	Notifications []struct{}    `json:"notifications,omitempty"`
	UserV         int           `json:"userV,omitzero"`
	AppVersion    string        `json:"appVersion,omitzero"`
}

// ListTasksData defines a model
type ListTasksData []ListTasksDataItems

// ListTasksDataItems defines a model
type ListTasksDataItems struct {
	UnderscoreID      uuid.UUID                 `json:"_id,omitzero"`
	Challenge         struct{}                  `json:"challenge"`
	Group             ListTasksDataItemsGroup   `json:"group"`
	Up                bool                      `json:"up,omitzero"`
	Down              bool                      `json:"down,omitzero"`
	CounterUp         int                       `json:"counterUp,omitzero"`
	CounterDown       int                       `json:"counterDown,omitzero"`
	Frequency         string                    `json:"frequency,omitzero"`
	History           ListTasksDataItemsHistory `json:"history,omitempty"`
	Type              string                    `json:"type,omitzero"`
	Notes             string                    `json:"notes,omitzero"`
	Tags              []uuid.UUID               `json:"tags,omitempty"`
	Value             float64                   `json:"value"`
	Priority          int                       `json:"priority,omitzero"`
	Attribute         string                    `json:"attribute,omitzero"`
	ByHabitica        bool                      `json:"byHabitica,omitzero"`
	Text              string                    `json:"text,omitzero"`
	Reminders         []struct{}                `json:"reminders,omitempty"`
	CreatedAt         time.Time                 `json:"createdAt,omitzero"`
	UpdatedAt         time.Time                 `json:"updatedAt,omitzero"`
	UserID            uuid.UUID                 `json:"userId,omitzero"`
	ID                uuid.UUID                 `json:"id,omitzero"`
	Repeat            *ListTasksDataItemsRepeat `json:"repeat,omitempty"`
	EveryX            *int                      `json:"everyX,omitempty"`
	Streak            *int                      `json:"streak,omitempty"`
	NextDue           []time.Time               `json:"nextDue,omitempty"`
	YesterDaily       bool                      `json:"yesterDaily,omitempty"`
	Completed         bool                      `json:"completed,omitempty"`
	CollapseChecklist bool                      `json:"collapseChecklist,omitempty"`
	StartDate         time.Time                 `json:"startDate,omitempty"`
	DaysOfMonth       []struct{}                `json:"daysOfMonth,omitempty"`
	WeeksOfMonth      []struct{}                `json:"weeksOfMonth,omitempty"`
	Checklist         []struct{}                `json:"checklist,omitempty"`
	IsDue             bool                      `json:"isDue,omitempty"`
}

// ListTasksDataItemsGroup defines a model
type ListTasksDataItemsGroup struct {
	Approval         ListTasksDataItemsGroupApproval `json:"approval"`
	AssignedUsers    []struct{}                      `json:"assignedUsers,omitempty"`
	SharedCompletion string                          `json:"sharedCompletion,omitzero"`
}

// ListTasksDataItemsGroupApproval defines a model
type ListTasksDataItemsGroupApproval struct {
	Required  bool `json:"required,omitzero"`
	Approved  bool `json:"approved,omitzero"`
	Requested bool `json:"requested,omitzero"`
}

// ListTasksDataItemsHistory defines a model
type ListTasksDataItemsHistory []ListTasksDataItemsHistoryItems

// ListTasksDataItemsHistoryItems defines a model
type ListTasksDataItemsHistoryItems struct {
	Date       int     `json:"date,omitzero"`
	Value      float64 `json:"value"`
	ScoredUp   int     `json:"scoredUp,omitzero"`
	ScoredDown int     `json:"scoredDown,omitzero"`
}

// ListTasksDataItemsRepeat defines a model
type ListTasksDataItemsRepeat struct {
	M  bool `json:"m,omitzero"`
	T  bool `json:"t,omitzero"`
	W  bool `json:"w,omitzero"`
	Th bool `json:"th,omitzero"`
	F  bool `json:"f,omitzero"`
	S  bool `json:"s,omitzero"`
	Su bool `json:"su,omitzero"`
}
